target-name: bugs.yaml
data-root:
  files:
    var/log/neutron/neutron-ovn-metadata-agent.log: |
      2022-02-06 05:47:20.754 1331249 ERROR neutron.agent.ovn.metadata.server AttributeError: 'MetadataProxyHandler' object has no attribute 'sb_idl'
  copy-from-original:
    - sos_commands/date/date
    - uptime
raised-bugs:
  https://bugs.launchpad.net/bugs/1928031: >-
    Known neutron-ovn bug identified that impacts OVN sbdb connections.
